### ISSUE TITLE
Feature Request: Apple Silicon / M1 / ARM Support

### ISSUE THREAD

**Issue by sammcj** [objective-see/OverSight#22]
Currently OverSight is compiled as Intel only, this causes high CPU utilisation on Apple Silicon (M1 / M1 Pro / M1 Max) based machines.

Would it be possible to have this built as a universal binary to support both Intel and ARM?

**Comment by kevindiu** [comment]
Seems version 2.0.1 supports apple silicon

**Comment by w3b6x9** [comment]
Confirming that v2.0.1 supports Apple Silicon. This feature request can be closed.

**Comment by sammcj** [comment]
Awesome! Thanks!
