### ISSUE TITLE
Taking too much memory like showing 16 gb++ 

### ISSUE THREAD

**Issue by krushnadeore** [objective-see/OverSight#24]
I just saw why my MacBook is lagging and it comes to know that in activity manager OverSightXPC this process taking 16 gb memory I don't know
 I just uninstalled oversight
version latest : 2.0
MacBook Air M1 macOS 12.1

feature request: add M1 support for objective see apps
<img width="567" alt="Screenshot 2022-01-02 at 3 19 45 PM" src="https://user-images.githubusercontent.com/73570192/147872227-81af7c32-0570-49f3-b030-6d5a9e4d263f.png">

**Comment by kevindiu** [comment]
I don't have this issue on my M1 MacBook Air, can you provide more details?

**Comment by sockshrimp** [comment]
I've got this issue on macOS 12.3.1 with Oversight v1.2.0
These screenshots were taken about 1 minute apart.
<img width="274" alt="Screen Shot 2022-04-06 at 06 53 02" src="https://user-images.githubusercontent.com/101304305/161852328-fefb3a79-21f9-4065-8053-3b23c6d66456.png">
<img width="281" alt="Screen Shot 2022-04-06 at 06 54 53" src="https://user-images.githubusercontent.com/101304305/161852349-0812ea60-12a0-4db2-aaa3-d86bacda54ae.png">

**Comment by objective-see** [comment]
This has been fixed in version 2.0+, which can be found in the [Release](https://github.com/objective-see/OverSight/releases/) page!
