### ISSUE TITLE
Version 2.0.0 installer not asking for root access

### ISSUE THREAD

**Issue by upekshapriya** [objective-see/OverSight#25]
> FAQs
Q: Why does the OverSight Installer need my password?
A: In order to determine what process(es) is/are using the webcam, OverSight interfaces with Apple's 'camera daemon.' This requires elevated privileges. Also if the user clicks, 'block' when a process is detected using the camera, OverSight will terminate the process. Again, this action (may) require elevated privileges.

And yet the Version 2.0.0 installer is not asking for root access, which would account for there being no notifications of access to the webcam and microphone when I check the video and mic in Zoom preferences.

On macOS 12.1

**Comment by objective-see** [comment]
Just released v2.1.0: https://github.com/objective-see/OverSight/releases/download/v2.1.0/OverSight_2.1.0.zip
...it should restore functionally that was lost/broken by changes by Apple to recent versions of macOS.

The currently method of monitoring the mic/webcam doesn't required root access anymore :) 
...I'll update the documentation/FAQs to clarify this shortly.
