### ISSUE TITLE
OverSight using huge amount of memory

### ISSUE THREAD

**Issue by Sr-Gonzalo** [objective-see/OverSight#3]
Hello, this is my first post to GitHub

OverSight version 1.2.0 has occasionally eaten up huge amounts of memory.  This has happened several times.   

I noticed the computer slowing down and unable to do normal tasks.  Activity Monitor would show OverSight using several GB of memory:  

![image](https://user-images.githubusercontent.com/79372358/108605827-7bc2f000-736b-11eb-808c-4e58a708ae34.png)

Planning to uninstall OverSight for now and watch for any updates.  Using a Mac OS 10.13.6 

**Mahalo!**

**Comment by eeston** [comment]
Having the same issue. I emailed the dev a few times but no response so far...

**Comment by RedEpicness** [comment]
Same issue for me, filled up 40GB of swap on my 16GB laptop. Seems to have started sometime around the release of Big Sur so it might be a bug with the new OS.

**Comment by Eagleo0** [comment]
It also uses a lot of CPU 
<img width="555" alt="CPU Usage" src="https://user-images.githubusercontent.com/9079111/115532474-1bcac600-a296-11eb-870a-92aa228c2745.png">

**Comment by GuillaumeDIDIER** [comment]
I've had intermittently the same issue.

Since updating on 11.3 it seems to have gotten worse

**Comment by ikiK-CRO** [comment]
Well i removed it. Same thing.

**Comment by grimabe** [comment]
Same behaviour using over 64GO over SWAP and MEMORY and one CPU AT Over 70% on MacOS 11.3

**Comment by freen** [comment]
Having the same issue. As soon as I opened the application it began using up as memory as it could. Hit at 15 GB RAM usage in minutes (I only have 8 GB physical RAM.)

CPU is also high, up to 60%.

![Captura de Pantalla 2021-04-30 a la(s) 7 18 48 a  m](https://user-images.githubusercontent.com/1816457/116688216-5dd5c500-a984-11eb-9d0f-b92a36fbd55d.png)

**Comment by objective-see** [comment]
just pushed a beta with fix (and lots of other improvements!)
https://github.com/objective-see/OverSight/releases/tag/v2.0.0_beta

...note that it only monitors camera for now (will add microphone back in shortly).

If you like to test/report any issues, I'd be stoked!

**Comment by grimabe** [comment]
@objective-see thanks for the update ! 
Only 25MB of RAM used for now, and 0% CPU. Quite an improvement 🎉
Let's see how it goes in the next few days :-)

**Comment by GuillaumeDIDIER** [comment]
Also installed the beta, will come back if I notice anything interesting. (Otherwise I'll likely forget to say anything, no news is good news, you can speculatively execute my Thanks)

**Comment by robspekschoor** [comment]
So far very stable and normal/light consumption of memory and cpu. Nice job!

**Comment by GuillaumeDIDIER** [comment]
I confirm :)

**Comment by jarolrod** [comment]
Confirming this ram and cpu issue on release v1.2.0. Both betas are huge improvements performance wise ([2.0.0](https://github.com/objective-see/OverSight/releases/tag/v2.0.0_beta), [2.0.0 Beta 2](https://github.com/objective-see/OverSight/releases/tag/v2.0.0_beta_2))

**Comment by objective-see** [comment]
...fixed in v2.0.0
