### ISSUE TITLE
ERROR: "[path] is not a valid action"

### ISSUE THREAD

**Issue by juekr** [objective-see/OverSight#31]
I am trying to run a script whenever the microphone or camera status changes but it won't be executed. Not even the simplest "/user/bin/touch /Users/juergen/test.txt" will run. In the Console.app I can see that OverSight tries to run the action but it throws an error "ERROR: /user/bin/touch /Users/juergen/test.txt is not a valid action". I've tried running a bash script without parameters, a PHP script with parameters, all in quotes or without quotes. Always to the same effect.

I'm on MacOS Monterey 12.5.1 on a Silicon M1 Mac Mini.

**Comment by objective-see** [comment]
Just released v2.1.0: https://github.com/objective-see/OverSight/releases/download/v2.1.0/OverSight_2.1.0.zip

This release includes improvements to this logic. 
...specifically the path to the item is now populated via a "Browse" / Select Panel to ensure the path is valid / can be executed. 

To keep things simple you can't specify your own arguments, though there is an option for OverSight to pass several relevant arguments to your script/app:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/11327812/202872694-fc542f24-1163-4b7e-9e50-9fe5a890f172.png">

Can you give this new release a test to confirm it addresses the issue? Mahalo! 🙏
