### ISSUE TITLE
Does the developer still take care about this solution?

### ISSUE THREAD

**Issue by damianino1** [objective-see/OverSight#32]
It is very sad as this app stopped to work serval months ago as I guess MacOS 12.4 has been released.
This issue has been reported here several times and I even sent an email to the developer..

Please take care about your solution and get it running again, we all love you app :)

**Comment by objective-see** [comment]
Working on it 😅
See commit: https://github.com/objective-see/OverSight/commit/8d3293dbf6fd72355926e751f8d0db6276093891

**Comment by objective-see** [comment]
Mahalo of your patience 🙏🏽

Just released v2.1.0: https://github.com/objective-see/OverSight/releases/download/v2.1.0/OverSight_2.1.0.zip
...can you give it a whirl and let me know if there are (still) any issues?
