### ISSUE TITLE
No alert / not working on webcam activation

### ISSUE THREAD

**Issue by Morgy93** [objective-see/OverSight#33]
Hello,

with the latest 2.0.2 release the app does not crash on macOS 12.6 - thanks!
But for me it does not work at all, I can enable my webcam from various places and no alert is shown.
The simplest test for me was using https://handmirror.app/
Using MacBook Pro (16-inch, 2021; Apple M1 Pro)

<img width="142" alt="image" src="https://user-images.githubusercontent.com/7961978/196954156-628c8da3-ca54-4ece-907d-72f2dcc6eed6.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/7961978/196954209-5d780aba-1dce-4271-8c06-d429468effa1.png">

No allowed items, default settings

<img width="587" alt="image" src="https://user-images.githubusercontent.com/7961978/196954530-04840194-bac7-4e39-a3a7-c36609ae0448.png">

Anything I can provide to help debugging?

**Comment by objective-see** [comment]
Thanks for the bug report.
Hrmm, odd, just tested on my machine (Mac M1 + macOS 12.6) and with HandMirror works as expected 🤔

Can you see if anything shows up in the system logs (`Console.app` filter on "OverSight")
...and what type type of Mac / version of macOS are you on?

Thanks!

**Comment by Morgy93** [comment]
> Can you see if anything shows up in the system logs (`Console.app` filter on "OverSight") ...and what type type of Mac / version of macOS are you on?

Nothing in the system.log for OverSight.

System Report:
Model Name:	MacBook Pro
Model Identifier:	MacBookPro18,1
Chip:	Apple M1 Pro
System Version:	macOS 12.6 (21G115)
Kernel Version:	Darwin 21.6.0

**Comment by damianino1** [comment]
I can confirm, unfortunately it's still buggy and doesn't work. A notification appears but it's not blocked and webcam works even I click on block.

**Comment by objective-see** [comment]
@damianino1 this is (now) expected behavior (on macOS 12.6). 

As noted in [this comment](https://github.com/objective-see/OverSight/issues/30#issuecomment-1285398276) as Apple censored the means to identify the process, while OverSight can alert you that a process has accessed the webcam it can no longer tell you which process is responsible ...which also means it cannot block said process 😫

I'll work on a solution once I'm home (traveling at the moment), though feel free also to submit a PR if there's an easy fix! 😇

**Comment by Morgy93** [comment]
I did the "have you tried everything all over again" thing.
For me it seems that it had something to do with the focus mode but at least it works now.

Will close this issue since it's fixed on my end. Thanks for your work!
