### ISSUE TITLE
Microphone became inactive "spam"

### ISSUE THREAD

**Issue by Morgy93** [objective-see/OverSight#36]
Hello,

since version 2.1.0 it sometimes "spams" the inactive message for the microphone and I have no clue why.
It seems that some application deactivates it, even if it has not been activated before.
Is it possible to see some debugging for the event?

**Comment by objective-see** [comment]
Thanks for the bug report!

This should be fixed in the latest (just released) version, v2.1.1, which you can grab from: https://github.com/objective-see/OverSight/releases/download/v2.1.1/OverSight_2.1.1.zip

Can you let me know if this addresses the issue? Mahalo 🙏

**Comment by Morgy93** [comment]
I saw the code changes, which should "fix" it.
Else I'll report back.

Thanks! Closed~
