### ISSUE TITLE
Execute is not working / Write an example of script execution

### ISSUE THREAD

**Issue by ivazin** [objective-see/OverSight#41]
I'm using version 2.1.5 but the execution is not working: tried python script, tried bash script with arguments and without it — no results.
Please explain how to use it correctly?

**Comment by objective-see** [comment]
The logs should provide more information, as to what is going wrong. 

From a terminal, can you first run: 
`log stream --level debug --predicate="subsystem='com.objective-see.oversight'"`

Then, set your the path to your script in the OverSight's preferences pane (tab: Action), and trigger a mic or cam event (e.g. open FaceTime, PhotoBooth, etc.).

You should then see something in the logs like such:

```
OverSight: [com.objective-see.oversight:application] executing user action
OverSight: [com.objective-see.oversight:application] execing task <path to your task> (arguments: (null))
OverSight: [com.objective-see.oversight:application] task completed with { }
```

**Comment by ivazin** [comment]
Thanks for all your help! It really helped to debug the script run ) Now it works! 🙏
