### ISSUE TITLE
Unable to execute node executable from action tab

### ISSUE THREAD

**Issue by brettjashford** [objective-see/OverSight#52]
![Screenshot 2023-08-30 at 11 34 32](https://github.com/objective-see/OverSight/assets/4293509/a484f452-1af0-4cd8-9fb9-4d49166941e1)

i'm unable to run a node executable from oversight. when i attempt to run the executable locally with the arguments added by oversight it works (logitech litra light turns on)  e.g. `/Users/brett/.nvm/versions/node/v18.14.2/bin/litra-oversight -device camera -event on`, but oversight does not appear to be calling the script. 

i updated the script to write to a file to see if it's being called at all from oversight and no file is written when my webcam turns on. i do see the notification from oversight. 

i updated the script to have full permissions `-rwxrwxrwx` (for debugging) 

thanks in advance for any help 🙏 

https://github.com/timrogers/litra#using-with-oversight

**Comment by objective-see** [comment]
Hrmm 🤔 

Can you try following to get more/debug info:

1. From the terminal, stream log messages via: 
`log stream --level debug --predicate="subsystem='com.objective-see.oversight'"`

2. Trigger a mic / camera event

3. Examine log output, which hopefully sheds more insight into why this is failing

...thanks!

**Comment by codylandry** [comment]
Hi! 👋 

I'm running into the same issue but I've tried both node and plain bash scripts.  I've also ensured the script file has `+x` and 777 perms as well.  

Here's some logs using the method you gave above:

```shell
2023-10-29 02:30:49.836267-0400 0x133436   Debug       0x0                  10748  0    OverSight: [com.objective-see.oversight:application] execing task /Users/codylandry/repos/scripts/script.sh (arguments: (
    "-device",
    microphone,
    "-event",
    off,
    "-activeCount",
    0
))
2023-10-29 02:30:49.837465-0400 0x133436   Debug       0x0                  10748  0    OverSight: [com.objective-see.oversight:application] task completed with {
}
```

Reallly hoping to get this resolved!  This app would be perfect for helping me automate some signalling to family so they know when my camera and mic is on while working from home.  Great job btw, besides this, it's working great.

**Comment by brettjashford** [comment]
i'm actually only using oversight for notifications and no longer need the execute functionality as logitech released an update to g hub to automatically toggle my light with the camera. @objective-see feel free to close or keep open for @codylandry's issue. thank you

**Comment by objective-see** [comment]
Fixed in the latest version 
...specifically in this commit: [fd2d903](https://github.com/objective-see/OverSight/commit/fd2d9033281545f9c19635cad6737e195a179fa2)

**Comment by gregpalaci** [comment]
Just for anyone looking to see all logs I made a one liner you can change the locations and the 777 permission but maybe it helps 😉

`touch ~/Documents/oversight.log && chmod 777 ~/Documents/oversight.log &&echo '#!/bin/bash \nlog stream --level debug --predicate="subsystem=`com.objective-see.oversight`" >> ~/Documents/oversight.log' >> ~/Documents/oversight.sh && chmod +x ~/Documents/oversight.sh
`
You would select the tickboxes as per above and navigate to the ".sh" which by default would be in Documents/oversight.sh

![Screenshot 2024-08-19 at 11 11 17 pm](https://github.com/user-attachments/assets/78a25ebd-59f6-4e42-922d-3d8eb3c94f17)
