### ISSUE TITLE
From macOS v14.0, application consumer is noted as “unknown”

### ISSUE THREAD

**Issue by clemlesne** [objective-see/OverSight#53]
# Current behavior

When a webcam app consumes the webcam, it is noted as “unknown”.

# Exerted behavior

App consumer should be noted as the app name and its PID.

# Versions

- Oversight v2.1.6
- macOS v14.0 (23A344)
- Webcam model: Elgato Facecam
- Application consumer: Microsoft Teams v1.6.00.26859

**Comment by benaltair** [comment]
![Screenshot 2023-10-23 at 8 20 39 PM](https://github.com/objective-see/OverSight/assets/17771229/c4b2c923-a3fb-4465-88dc-27ab9daea097)
All alerts show as `unknown` processes, severely reducing the usability of the application.

**Comment by objective-see** [comment]
<img width="362" alt="image" src="https://github.com/objective-see/OverSight/assets/11327812/ca634aff-317a-4b4a-ba4d-7c0f2b744dc2">

Thanks for the bug report, just released a new version that now (fully) compatible w/ macOS 14/Sonoma

**Comment by clemlesne** [comment]
I still have, in v2.2.2, unknown process name. I cannot know which app is consuming what.

<img width="353" alt="Screenshot 2023-12-11 at 10 46 56" src="https://github.com/objective-see/OverSight/assets/10001945/2aadd6c1-721c-4ab1-9a36-9b30148131aa">
