### ISSUE TITLE
No longer able to Execute a script or binary

### ISSUE THREAD

**Issue by mega-joe** [objective-see/OverSight#54]
I'm running OverSight v2.1.7 on Sonoma 14.1 with a M1 Pro MacBook. Oversight is identifying camera/mic activity and notifications are showing properly. But whatever I specify for the "Execute" option no longer runs. I've tried running a variety of executables and scripts. Nothing happens. It's been working fine prior to the latest version of OverSight and MacOS (not sure which broke it).

This is the whole reason I use Oversight. I have a script that turns on USB lighting when the camera turns on (and turns off the lighting when the camera is off). It was great when it worked.

**Comment by objective-see** [comment]
Thanks for the bug report.
...turns out there was a bug in a merged PR 😔

Just checked in a fix, will build/test/release first thing tomorrow AM!

**Comment by objective-see** [comment]
Fixed in the just released [v2.1.8](https://github.com/objective-see/OverSight/releases/download/v2.1.8/OverSight_2.1.8.zip)

**Comment by mega-joe** [comment]
THANK YOU. Everything is working again.
