### ISSUE TITLE
Automatic update is broken

### ISSUE THREAD

**Issue by n-thumann** [objective-see/OverSight#55]
I've noticed that the automatic update is broken. When I click the `Check Now` button in the `Update` tab of the settings, it says that `Installed version (2.1.6), is the latest)`, even though it isn't.

I had a quick look at the code and https://objective-see.org/products.json might be the issue, because it says that Oversight 2.1.5 is the latest release.

**Comment by objective-see** [comment]
I've just updated `products.json`, so the update should now be picked up.
