### ISSUE TITLE
OverSightXPC peaks CPU usage on 11.3

### ISSUE THREAD

**Issue by markthehipster** [objective-see/OverSight#6]
Hey there, 

Since MacOS 11.3 update, OverSightXPC process seems to use around 70% cpu on multiple threads. CPU temp also hovers between 80-99 celsius with fans ramping up every minute above 4500 rpm.
<img width="993" alt="image" src="https://user-images.githubusercontent.com/46720448/116227139-179a1f00-a754-11eb-96dc-a13b9680d3e3.png">
OverSight 1.20 on Intel MBP 2018 15' base model.

Quitting OverSight allows the Mac to go silent with 2000 rpm.

Thanks, 
Mark

**Comment by p33t3r** [comment]
Same here.

**Comment by FlxVctr** [comment]
Can confirm, also starts to use up all RAM and running into swap after a while.

**Comment by beka** [comment]
I have the same issue

<img width="595" alt="Screenshot 2021-04-28 at 22 25 20" src="https://user-images.githubusercontent.com/644909/116454417-0561d300-a871-11eb-803e-9d22646f3be3.png">

**Comment by barche** [comment]
Same issue on a 2018 Macbook Air

**Comment by silllli** [comment]
Same issue here.

**Comment by swiknaba** [comment]
Same here on 11.3 since the latest security update. Consumes 40GB of RAM and 100% CPU.

**Comment by freen** [comment]
Same issue. macOS 11.3 and OverSight v 1.2.0. RAM maxing out and CPU spiking to 60%.

**Comment by JayBrown** [comment]
Yep, same here. The XPC is at 50 to 60% CPU, and the helper at 6 to 7%. In my case I noticed this when recording mp3 with ffmpeg using an Automator workflow.

(2018 Intel MBP i9)

**Comment by objective-see** [comment]
Not sure what (yet), but clearly something in macOS 11.3 triggering an issue/bug in OverSight. Sorry! 😥
Digging into cause and will push out fix ASAP! Mahalo for your patience.

**Comment by octavian2204** [comment]
Hi, just to confirm that after update to 11.3 indeed the app becomes hell: 

<img width="1440" alt="Screen Shot 2021-05-01 at 18 37 53" src="https://user-images.githubusercontent.com/8106031/116787427-9a9cdb80-aaac-11eb-93c0-e09a5d6a31fe.png">

**Comment by MarcLaf** [comment]
Glad I'm not the only one! Took me a bit to find out why the latest update was causing massive battery drain and sluggish performance but once I saw this running so high I investigated.

**Comment by objective-see** [comment]
ok, beta with fix (and lots of other improvements!)
https://github.com/objective-see/OverSight/releases/tag/v2.0.0_beta

...note only monitors camera for now (will add microphone back in shortly). 

If you like to test/report any issues, I'd be stoked!

**Comment by swiknaba** [comment]
2.0.0 runs stable so far :-)

**Comment by MarcLaf** [comment]
Got Error on installation.
"May  3 20:10:43 laptop com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.system): com.objective-see.oversight.uninstallHelper (lint): Assuming EnablePressuredExit=false given EnableTransactions=false."

**Comment by objective-see** [comment]
@MarcLaf, from the Terminal, can you run:
`log show --predicate="subsystem='com.objective-see.oversight'"`

...should provide more detailed error info. Thanks!

**Comment by MarcLaf** [comment]
Ah that worked - I tried the command you had over on the main site (linked from the ? in the error message) but it just sat there.
```
2021-05-03 20:10:45.851457-0400 0xb2d0    Error    0x1f7ce   1784   0    com.objective-see.oversight.uninstallHelper: [com.objective-see.oversight:installer (helper)] ERROR: failed to execute config script 
configure.sh (1)
```

**Comment by ztepsa** [comment]
Both macOS 11.3 and 11.3.1 have issues with version 1.20.0, but 2.0-beta is working without any problems so far 🚀

**Comment by p4checo** [comment]
Thanks for the quick update! 🙌🏼  

I've managed to install 2.0.0 after it having failed once, however I'm getting a warning from Little Snitch telling me the app is in translocation mode, which doesn't allow me to create permanent rules 😢. I'm launching it from the `/Applications` folder, so I don't understand why this is happening.

![Screen Shot 2021-05-04 at 14 57 02](https://user-images.githubusercontent.com/1391324/117014925-2f8c1880-ace9-11eb-9171-c84022a4f320.png)

During install BlockBlock also points to a file in the app translocation folder, so perhaps that's related:

![Screen Shot 2021-05-04 at 15 02 36](https://user-images.githubusercontent.com/1391324/117015726-e7212a80-ace9-11eb-8498-97be42a1a26a.png)

**Comment by robspekschoor** [comment]
Looks really good so far. Indeed, had issue with installing it by upgrade. after uninstall it worked

**Comment by m3m3nt0m0ri** [comment]
Had the same overheating issue. Installed 2.0.0 beta and hopefully it fixes the heating issue.
The install went smoothly.

**Comment by 0xmachos** [comment]
Fixed for me in `v2.0.0` Beta 2

**Comment by Chasapple4** [comment]
> ![Screen Shot 2021-05-04 at 14 57 02](https://user-images.githubusercontent.com/1391324/117014925-2f8c1880-ace9-11eb-9171-c84022a4f320.png)

Might be the update checker, I did ask if that was what it was, Lulu cut off the end of the url

2.0 does fix the performance bug.

**Comment by JayBrown** [comment]
Afaik sentry.io is telemetry & bug reports, so we should allow connections, because it helps Patrick improve the software.

**Comment by swiknaba** [comment]
The "problem" in the screenshot --at least to me-- is, that due to the app running in this "App Translocation" we can't allow this request "for ever" but have to approve it with each restart of the app. Quite an annoyance.

**Comment by p4checo** [comment]
> The "problem" in the screenshot --at least to me-- is, that due to the app running in this "App Translocation" we can't allow this request "for ever" but have to approve it with each restart of the app. Quite an annoyance.

That's precisely it ☝🏼 Thank you 😄

**Comment by JayBrown** [comment]
That's weird, because the app and its installer are notarized. So there should be no translocation. You can run `xattr -l /Applications/OverSight.app`, and if the output says `com.apple.quarantine`, you should remove the XA with `xattr -dr com.apple.quarantine /Applications/OverSight.app`. At any rate, I have not problems on my system, i.e. no translocation.

**Comment by mteece** [comment]
Glad I found this thread. Current Intel based MacBook Pro on 11.3.1 with OverSight consuming 4.23GB of memory on a regular basis. Installed the 2.0.0-Beta and so far so good 👍🏻

**Comment by p4checo** [comment]
> That's weird, because the app and its installer are notarized. So there should be no translocation. You can run xattr -l /Applications/OverSight.app, and if the output says com.apple.quarantine, you should remove the XA with xattr -dr com.apple.quarantine /Applications/OverSight.app. At any rate, I have not problems on my system, i.e. no translocation.

Thanks for the tip! 🙏🏼 

Mine did in fact still say `com.apple.quarantine`:
`com.apple.quarantine: <4 digit code>;<8 digit code>;Firefox;<UUID>`

Running that command cleared it. Not sure what caused this on my system though 🤷🏼

**Comment by p4checo** [comment]
On a separate note, those already on 2.0.0-Beta - Does OverSight detect (and request) microphone access? On my system only camera access is requested (e.g. Zoom, Safari via Hangouts), which I'm finding weird 🤔 

macOS Big Sur 11.3 (20E232)
MacBookPro16,1

**Comment by swiknaba** [comment]
@p4checo I'm running https://github.com/objective-see/OverSight/releases/tag/v2.0.0 and both, camera and mic access are detected. **however**.
I have 2 mics:
1) the internal one -> I can allow/deny the access
![image](https://user-images.githubusercontent.com/20702503/118865564-5c435100-b8e1-11eb-8907-7ff41e1891ce.png)

2) an external mic plugged in via USB -> I only get the message, that this device became active, but I can only choose "ok":
![image](https://user-images.githubusercontent.com/20702503/118865496-49c91780-b8e1-11eb-83f7-c22dfbc75210.png)

**Comment by p4checo** [comment]
@swiknaba no luck here 😢 I only use the internal/built-in one, and it doesn't detect whether using the Mac's mic or one connected externally (e.g. apple earplugs cord mic). 

Already tried erasing OverSight's preferences (`com.objective-see.oversight.plist`), removed all rules, still no mic detection.
