### ISSUE TITLE
BlockBlock Helper 2.2.0 hangs on open

### ISSUE THREAD

**Issue by Chasapple4** [objective-see/OverSight#60]
macOS 11.7.10
Can't get a sample as Activity Monitor hangs 

BlockBlock background process is not hanging

**Comment by objective-see** [comment]
Thanks for the bug report! 
Any other info (macOS version)/steps to repo? (clean install, upgrade, etc etc).

Will keep testing on this end.

**Comment by objective-see** [comment]
Oh, and one more idea:

Can you run: `log stream | grep BlockBlock` from a terminal, and then try to (re)install/repo? This should give more information / what it going wrong. Thank you!

**Comment by Chasapple4** [comment]
Upgrade from Version 2.1.5

Strange this is supposed to be in https://github.com/objective-see/BlockBlock/issues but GitHub moved it for some reason

**Comment by Chasapple4** [comment]
Fixed in 2.2.1
