### ISSUE TITLE
Camera always shows as active on M1 MacBook Pro

### ISSUE THREAD

**Issue by mourke** [objective-see/OverSight#7]
My camera is always shown as being on even when I freshly boot into macOS and nothing can be using it. I'm on a completely fresh install on my new MacBook. As a result notifications are not always sent when the camera actually becomes active. 

Microphone alerts are working fine

**Comment by objective-see** [comment]
Sorry this is a bug in macOS :(  
They broke something on Big Sur, on M1. 

...it has been reported to Apple, so awaiting on them to fix it (but working on a workaround in the meantime)

**Comment by objective-see** [comment]
fixed via a workaround, in version 2.0+
